<?php

namespace App\Backend\DataSource\Console;

use App\Shared\DataSource\Facade\DataSourceFacadeInterface;
use App\Shared\Generated\DTO\DataSource\DataSourceCreateTransfer;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class CreateDataSourceCommand extends Command
{
    public function __construct(private readonly DataSourceFacadeInterface $dataSourceFacade)
    {
        parent::__construct('pp:ds:create');
    }

    public function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }

    public function execute(InputInterface $input, OutputInterface $output)
    {
        $request = new DataSourceCreateTransfer();
        $request->setName('Demo');
        $request->setType('http');

        $response = $this->dataSourceFacade->createDataSource($request);

        $output->writeln(json_encode($response, JSON_PRETTY_PRINT));

        return Command::SUCCESS;
    }
}