<?php

namespace App\Saga\VideoUpload;

use Micro\Component\DependencyInjection\Container;
use Micro\Framework\Kernel\Plugin\AbstractPlugin;
use Micro\Plugin\Console\CommandProviderInterface;

class VideoUploadSagaPlugin extends AbstractPlugin implements CommandProviderInterface
{
    public function provideDependencies(Container $container): void
    {
        parent::provideDependencies($container); // TODO: Change the autogenerated stub
    }

    public function provideConsoleCommands(Container $container): array
    {
        return [
        ];
    }
}