version: "2.7"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php /app/bin/console.php test:saga:execute"

temporal:
  address: "temporal:7233"
  activities:
    num_workers: 4

logs:
  level: panic
  mode: production
