routes:
  plugins:
    resource: ./plugins_secured.yaml
    format: yaml
    options:
      handler:
        request:
          - App\Frontend\Security\Handler\Request\RequestHeaderAuthenticateHandler
        response:
          - App\Frontend\Common\ResponseTransformer\ResponseTransformerHandler
          - App\Frontend\Common\ResponseTransformer\TemporalExceptionHandler
          - App\Frontend\Common\ResponseTransformer\ResponseExceptionHandler

  security:
    resource: '@SecurityPluginFrontend/Resource/routing/routing.yaml'
    format: yaml
    prefix: /api/security
    options:
      handler:
        response:
          - App\Frontend\Common\ResponseTransformer\ResponseTransformerHandler
          - App\Frontend\Common\ResponseTransformer\ResponseExceptionHandler