routes:
  plugins:
    resource: ./plugins_secured.yaml
    format: yaml
    options:
      handler:
        request:
          - App\Frontend\Common\Authenticate\RequestHandler\AuthenticateRequestCookieHandler
        response:
          - App\Frontend\Common\ResponseTransformer\ResponseTransformerHandler
          - App\Frontend\Common\ResponseTransformer\ResponseExceptionHandler

  security:
    resource: '@HttpSecurityPlugin/Resource/routing/routing.yaml'
    prefix: /security
    format: yaml
    options:
      security:
        provider: api